### PR TITLE
Student form

### PR DESCRIPTION
**Pull request by bchugg**
Main addition is to add a student intake form accessible from login page

### CODE REVIEW

**Comment by angadkalra** [comment]
@bchugg Everything looks good and works great. When I turned debug mode off, some styling stuff went haywire, like the position of footer and other text. Does that happen to you?

EDIT: Just saw terminal output when running on localhost, and all the static file requests are getting a 404. Does that happen to you?

**Comment by angadkalra** [comment]
Running "python manage.py runserver --insecure" allows the static files to be served locally when Debug=False. However, is it okay for Debug=False to break the static file access when running localhost normally? I still feel like our static file setup is wrong because static_root is commented out  and most tutorials include it. I don't know. Tell me what you think.

**Comment by bchugg** [comment]
Yeah I agree that we have some weird stuff going on with our static files. How does Heroku serve them? The problem might be that we have to run `collectstatic`.

**Comment by angadkalra** [comment]
I couldn't run collectstatic because our settings.py is missing a static root.

**Comment by bchugg** [comment]
Okay I'll try putting the static root back in and then fixing the js issues.

**Pull request merged**
